export const kenyabanks = [
  {
    name: "KCB Bank Kenya Limited",
    code: "01",
    bankCode: "KCBLKENXXXX",
  },
  {
    name: "Standard Chartered Bank",
    code: "02",
    bankCode: "SCBLKENXXXX",
  },
  {
    name: "ABSA Bank Kenya PLC",
    code: "03",
    bankCode: "BARCKENXXXX",
  },
  {
    name: "Bank of India",
    code: "05",
    bankCode: "BKIDKENAXXX",
  },
  {
    name: "Bank of Baroda (Kenya) Ltd",
    code: "06",
    bankCode: "BARBKENAXXX",
  },
  {
    name: "NCBA Kenya PLC",
    code: "07",
    bankCode: "CBAFKENXXXX",
  },
  {
    name: "HABIB BANK ltd",
    code: "08",
    bankCode: "HABBKENXXXX",
  },
  {
    name: "Prime Bank Ltd",
    code: "10",
    bankCode: "PRIEKENXXXX",
  },
  {
    name: "Co-operative Bank of Kenya Limited",
    code: "11",
    bankCode: "KCOOKENAXXX",
  },
  {
    name: "National Bank of Kenya Ltd",
    code: "12",
    bankCode: "NBKEKENXXXX",
  },
  {
    name: "M-Oriental Bank Limited",
    code: "14",
    bankCode: "MORBKENAXXX",
  },
  {
    name: "Citibank N.A. Kenya",
    code: "16",
    bankCode: "CITIKENAXXX",
  },
  {
    name: "Habib Bank AG Zurich",
    code: "17",
    bankCode: "HBZUKENA",
  },
  {
    name: "Middle East Bank Kenya Limited",
    code: "18",
    bankCode: "MIEKKENAXXX",
  },
  {
    name: "Bank of Africa Kenya Limited",
    code: "19",
    bankCode: "AFRIKENXXXX",
  },
  {
    name: "Consolidated Bank of Kenya Ltd",
    code: "23",
    bankCode: "CONKENAXXX",
  },
  {
    name: "Credit Bank Limited",
    code: "25",
    bankCode: "CRBTKENAXXX",
  },
  {
    name: "Access Bank (Kenya) Limited",
    code: "26",
    bankCode: "ABNGKENAXXX",
  },
  {
    name: "Chase Bank (K) Limited",
    code: "30",
    bankCode: "CKENKENAXXX",
  },
  {
    name: "Stanbic Bank Kenya Limited",
    code: "31",
    bankCode: "SBICKENXXXX",
  },
  {
    name: "African Banking Corporation Limited",
    code: "35",
    bankCode: "ABCLKENAXXX",
  },
  {
    name: "Imperial Bank Ltd",
    code: "39",
    bankCode: "IMPLKENA",
  },
  {
    name: "Ecobank Kenya Limited",
    code: "43",
    bankCode: "ECOCKENAXXX",
  },
  {
    name: "CARITAS",
    code: "48",
    bankCode: "FABLKENAXXX",
  },
  {
    name: "Spire Bank Ltd",
    code: "49",
    bankCode: "SPBLKENAXXX",
  },
  {
    name: "Paramount Bank Limited",
    code: "50",
    bankCode: "PAUTKENAXXX",
  },
  {
    name: "Kingdom Bank Limited",
    code: "51",
    bankCode: "CIFIKENAXXX",
  },
  {
    name: "Guaranty Trust Bank (Kenya) Limited",
    code: "53",
    bankCode: "GTBIKENAXXX",
  },
  {
    name: "Victoria Commercial Bank Limited",
    code: "54",
    bankCode: "VICMKENAXXX",
  },
  {
    name: "Guardian Bank Limited",
    code: "55",
    bankCode: "GUARKENAXXX",
  },
  {
    name: "INVESTMENT & MORGAGES BANK",
    code: "57",
    bankCode: "IMBLKENAXXX",
  },
  {
    name: "Development Bank of Kenya Ltd",
    code: "59",
    bankCode: "DEVKKENA",
  },
  {
    name: "SBM Bank (Kenya) Limited",
    code: "60",
    bankCode: "SBMKKENAXXX",
  },
  {
    name: "Diamond Trust Bank (K) Limited",
    code: "63",
    bankCode: "DTKEKENAXXX",
  },
  {
    name: "Charterhouse Bank Ltd",
    code: "64",
    bankCode: "CHBLKEN1XXX",
  },
  {
    name: "CENTRAL BANK OF KENYA",
    code: "65",
    bankCode: "CBKEKENXXXX ",
  },
  {
    name: "Mayfair CIB Bank Limited",
    code: "65",
    bankCode: "MYBKKENAXXX",
  },
  {
    name: "Sidian Bank Limited",
    code: "66",
    bankCode: "SIDNKENAXXX",
  },
  {
    name: "Equity Bank Kenya Limited",
    code: "68",
    bankCode: "EQBLKENAXXX",
  },
  {
    name: "Family Bank Limited",
    code: "70",
    bankCode: "FABLKENAXXX",
  },
  {
    name: "Gulf African Bank Limited",
    code: "72",
    bankCode: "GAFRKENAXXX",
  },
  {
    name: "First Community Bank Ltd",
    code: "74",
    bankCode: "IFCBKENAXXX",
  },
  {
    name: "DIB Bank Kenya Limited",
    code: "75",
    bankCode: "DUIBKENAXXX",
  },
  {
    name: "UBA Kenya Bank Limited",
    code: "76",
    bankCode: "UNAFKENAXXX",
  },
  {
    name: "HFC Limited",
    code: "83",
    bankCode: "HFCOKENAXXX",
  },
  {
    name: "ChoiceMFB",
    code: "36",
    bankCode: "CIFIKENAXXX",
  },
  {
    name: "CIB KENYA LIMITED",
    code: "65",
    bankCode: "MYBKKENAXXX ",
  },
  {
    name: "Faulu",
    code: "79",
    bankCode: "FAUMKENAXXX",
  },
  {
    name: "HOUSING FINANCE",
    code: "61",
    bankCode: "HFCOKENAXXX",
  },
  {
    name: "KENYA WOMEN MICROFINANCE BANK",
    bankCode: "KWMIKENXXXX",
    code: "78",
  },
  {
    name: "LOOP",
    bankCode: "CBAFKENX",
    code: "138",
  },
  {
    name: "Stima Sacco",
    bankCode: "KCOOKENAXXX",
    code: "89",
  },
  {
    name: "UMBA",
    bankCode: "CBAKENX",
    code: "67",
  },
  {
    name: "UNAITAS",
    bankCode: "ABCLKENAXXX",
    code: "32",
  },
  {
    name: "VOOMA",
    bankCode: "KCBLKENAXXX",
    code: "93",
  },
];
export const tanzaniaBanks = [
  { name: "ACCESS BANK TANZANIA" },
  { name: "ADVANS BANK TANZANIA" },
  { name: "AFRICAN BANKING CORPORATION TANZANIA" },
  { name: "AKIBA COMMERCIAL BANK" },
  { name: "AMANA BANK" },
  { name: "AZANIA BANK" },
  { name: "BANK M TANZANIA PUBLIC LIMITED" },
  { name: "BANK OF AFRICA TANZANIA" },
  { name: "BANK OF BARODA (TANZANIA)" },
  { name: "BANK OF INDIA (TANZANIA)" },
  { name: "BANK OF TANZANIA" },
  { name: "BARCLAYS BANK OF TANZANIA" },
  { name: "CANARA BANK OF TANZANIA" },
  { name: "CHINA COMMERCIAL BANK" },
  { name: "CITIBANK" },
  { name: "COMMERCIAL BANK OF AFRICA (TANZANIA)" },
  { name: "CRDB BANK" },
  { name: "DIAMOND TRUST BANK TANZANIA" },
  { name: "ECOBANK" },
  { name: "ECO BANK" },
  { name: "EFATHA BANK LIMITED" },
  { name: "EQUITY BANK (TANZANIA)" },
  { name: "EXIM BANK (TANZANIA)" },
  { name: "FINCA MICROFINANCE BANK LIMITED" },
  { name: "FIRST NATIONAL BANK OF TANZANIA" },
  { name: "GUARANTY TRUST BANK" },
  { name: "HABIB AFRICAN BANK" },
  { name: "I&M BANK TANZANIA" },
  { name: "INTERNATIONAL COMMERCIAL BANK" },
  { name: "KCB BANK TANZANIA" },
  { name: "KILIMANJARO CO-OPERATIVE BANK" },
  { name: "MAENDELEO BANK" },
  { name: "MERU COMMUNITY BANK LTD" },
  { name: "MKOMBOZI NATIONAL BANK" },
  { name: "MUCOBA BANK PLC" },
  { name: "MWALIMU COMMERCIAL BANK" },
  { name: "MWANGA COMMUNITY BANK" },
  { name: "NATIONAL MICROFINANCE BANK" },
  { name: "NBC LIMITED" },
  { name: "NIC BANK TANZANIA" },
  { name: "PEOPLE'S BANK OF ZANZIBAR" },
  { name: "STANBIC BANK TANZANIA LIMITED" },
  { name: "STANDARD CHARTERED BANK" },
  { name: "TANZANIA AGRICULTURAL DEVELOPMENT" },
  { name: "TANZANIA POSTAL BANK" },
  { name: "TANZANIA WOMEN'S BANK LTD" },
  { name: "TIB CORPORATE BANK" },
  { name: "TWIGA BANCORP LIMITED" },
  { name: "UBL BANK TANZANIA LIMITED" },
  { name: "UCHUMI COMMERCIAL BANK" },
  { name: "UNITED BANK FOR AFRICA" }
];
export const ugandaBanks = [
  { name: "ABC CAPITAL BANK LIMITED" },
  { name: "BANK OF AFRICA - UGANDA LIMITED" },
  { name: "BARCLAYS BANK OF UGANDA LIMITED" },
  { name: "BANK OF BARODA (UGANDA) LIMITED" },
  { name: "BANK OF INDIA (UGANDA) LIMITED" },
  { name: "CAIRO INTERNATIONAL BANK LIMITED" },
  { name: "CENTERARY RURAL DEVELOPMENT BANK" },
  { name: "CITIBANK UGANDA LIMITED" },
  { name: "COMMERCIAL BANK OF AFRICA UGANDA" },
  { name: "DFCU BANK LIMITED" },
  { name: "DIAMOND TRUST BANK UGANDA LIMITED" },
  { name: "EAST AFRICAN DEVELOPMENT BANK" },
  { name: "ECOBANK UGANDA LIMITED" },
  { name: "EQUITY BANK UGANDA LIMITED" },
  { name: "EXIM BANK (UGANDA) LIMITED" },
  { name: "FINCA BANK UGANDA" },
  { name: "FINANCE TRUST BANK LTD" },
  { name: "GUARANTY TRUST BANK LTD" },
  { name: "HOUSING FINANCE BANK LTD" },
  { name: "KCB BANK UGANDA LTD" },
  { name: "MERCANTILE CREDIT BANK" },
  { name: "NCBA BANK UGANDA BANK" },
  { name: "ORIENT BANK" },
  { name: "OPPORTUNITY BANK UGANDA LTD" },
  { name: "POSTBANK UGANDA" },
  { name: "PRIDE MICROFINANCE BANK" },
  { name: "STANBIC BANK UGANDA LIMITED" },
  { name: "STANDARD CHARTERED BANK UGANDA" },
  { name: "TOP FINANCE BANK UGANDA LIMITED" },
  { name: "TROPICAL BANK LIMITED" },
  { name: "UNITED BANK FOR AFRICA (UGANDA)" }
];


export const allBanks = [
  {
    name: "KCB Bank Kenya Limited",
    code: "01",
    bankCode: "KCBLKENXXXX",
  },
  {
    name: "Standard Chartered Bank",
    code: "02",
    bankCode: "SCBLKENXXXX",
  },
  {
    name: "ABSA Bank Kenya PLC",
    code: "03",
    bankCode: "BARCKENXXXX",
  },
  {
    name: "Bank of India",
    code: "05",
    bankCode: "BKIDKENAXXX",
  },
  {
    name: "Bank of Baroda (Kenya) Ltd",
    code: "06",
    bankCode: "BARBKENAXXX",
  },
  {
    name: "NCBA Kenya PLC",
    code: "07",
    bankCode: "CBAFKENXXXX",
  },
  {
    name: "HABIB BANK ltd",
    code: "08",
    bankCode: "HABBKENXXXX",
  },
  {
    name: "Prime Bank Ltd",
    code: "10",
    bankCode: "PRIEKENXXXX",
  },
  {
    name: "Co-operative Bank of Kenya Limited",
    code: "11",
    bankCode: "KCOOKENAXXX",
  },
  {
    name: "National Bank of Kenya Ltd",
    code: "12",
    bankCode: "NBKEKENXXXX",
  },
  {
    name: "M-Oriental Bank Limited",
    code: "14",
    bankCode: "MORBKENAXXX",
  },
  {
    name: "Citibank N.A. Kenya",
    code: "16",
    bankCode: "CITIKENAXXX",
  },
  {
    name: "Habib Bank AG Zurich",
    code: "17",
    bankCode: "HBZUKENA",
  },
  {
    name: "Middle East Bank Kenya Limited",
    code: "18",
    bankCode: "MIEKKENAXXX",
  },
  {
    name: "Bank of Africa Kenya Limited",
    code: "19",
    bankCode: "AFRIKENXXXX",
  },
  {
    name: "Consolidated Bank of Kenya Ltd",
    code: "23",
    bankCode: "CONKENAXXX",
  },
  {
    name: "Credit Bank Limited",
    code: "25",
    bankCode: "CRBTKENAXXX",
  },
  {
    name: "Access Bank (Kenya) Limited",
    code: "26",
    bankCode: "ABNGKENAXXX",
  },
  {
    name: "Chase Bank (K) Limited",
    code: "30",
    bankCode: "",
  },
  {
    name: "Stanbic Bank Kenya Limited",
    code: "31",
    bankCode: "SBICKENXXXX",
  },
  {
    name: "African Banking Corporation Limited",
    code: "35",
    bankCode: "ABCLKENAXXX",
  },
  // {
  //   name: "Imperial Bank Ltd",
  //   code: "39",
  //   bankCode: "",
  // },
  {
    name: "Ecobank Kenya Limited",
    code: "43",
    bankCode: "ECOCKENAXXX",
  },
  {
    name: "CARITAS",
    code: "48",
    bankCode: "FABLKENAXXX",
  },
  {
    name: "Spire Bank Ltd",
    code: "49",
    bankCode: "SPBLKENAXXX",
  },
  {
    name: "Paramount Bank Limited",
    code: "50",
    bankCode: "PAUTKENAXXX",
  },
  {
    name: "Kingdom Bank Limited",
    code: "51",
    bankCode: "CIFIKENAXXX",
  },
  {
    name: "Guaranty Trust Bank (Kenya) Limited",
    code: "53",
    bankCode: "GTBIKENAXXX",
  },
  {
    name: "Victoria Commercial Bank Limited",
    code: "54",
    bankCode: "VICMKENAXXX",
  },
  {
    name: "Guardian Bank Limited",
    code: "55",
    bankCode: "GUARKENAXXX",
  },
  {
    name: "INVESTMENT & MORGAGES BANK",
    code: "57",
    bankCode: "IMBLKENAXXX",
  },
  {
    name: "Development Bank of Kenya Ltd",
    code: "59",
    bankCode: "DEVKKENA",
  },
  {
    name: "SBM Bank (Kenya) Limited",
    code: "60",
    bankCode: "SBMKKENAXXX",
  },
  {
    name: "Diamond Trust Bank (K) Limited",
    code: "63",
    bankCode: "DTKEKENAXXX",
  },
  {
    name: "Charterhouse Bank Ltd",
    code: "64",
    bankCode: "",
  },
  {
    name: "CENTRAL BANK OF KENYA",
    code: "65",
    bankCode: "CBKEKENXXXX ",
  },
  {
    name: "Mayfair CIB Bank Limited",
    code: "65",
    bankCode: "MYBKKENAXXX",
  },
  {
    name: "Sidian Bank Limited",
    code: "66",
    bankCode: "SIDNKENAXXX",
  },
  {
    name: "Equity Bank Kenya Limited",
    code: "68",
    bankCode: "EQBLKENAXXX",
  },
  {
    name: "Family Bank Limited",
    code: "70",
    bankCode: "FABLKENAXXX",
  },
  {
    name: "Gulf African Bank Limited",
    code: "72",
    bankCode: "GAFRKENAXXX",
  },
  {
    name: "First Community Bank Ltd",
    code: "74",
    bankCode: "IFCBKENAXXX",
  },
  {
    name: "DIB Bank Kenya Limited",
    code: "75",
    bankCode: "DUIBKENAXXX",
  },
  {
    name: "UBA Kenya Bank Limited",
    code: "76",
    bankCode: "UNAFKENAXXX",
  },
  {
    name: "HFC Limited",
    code: "83",
    bankCode: "HFCOKENAXXX",
  },
  {
    name: "ChoiceMFB",
    code: "36",
    bankCode: "CIFIKENAXXX",
  },
  {
    name: "CIB KENYA LIMITED",
    code: "65",
    bankCode: "MYBKKENAXXX ",
  },
  {
    name: "Faulu",
    code: "79",
    bankCode: "FAUMKENAXXX",
  },
  {
    name: "HOUSING FINANCE",
    code: "61",
    bankCode: "HFCOKENAXXX",
  },
  {
    name: "KENYA WOMEN MICROFINANCE BANK",
    bankCode: "KWMIKENXXXX",
    code: "78",
  },
  {
    name: "LOOP",
    bankCode: "CBAFKENX",
    code: "138",
  },
  {
    name: "Stima Sacco",
    bankCode: "KCOOKENAXXX",
    code: "89",
  },
  {
    name: "UMBA",
    bankCode: "CBAKENX",
    code: "67",
  },
  {
    name: "UNAITAS",
    bankCode: "ABCLKENAXXX",
    code: "32",
  },
  {
    name: "VOOMA",
    bankCode: "KCBLKENAXXX",
    code: "93",
  },
  { name: "ACCESS BANK TANZANIA" },
  { name: "ADVANS BANK TANZANIA" },
  { name: "AFRICAN BANKING CORPORATION TANZANIA" },
  { name: "AKIBA COMMERCIAL BANK" },
  { name: "AMANA BANK" },
  { name: "AZANIA BANK" },
  { name: "BANK M TANZANIA PUBLIC LIMITED" },
  { name: "BANK OF AFRICA TANZANIA" },
  { name: "BANK OF BARODA (TANZANIA)" },
  { name: "BANK OF INDIA (TANZANIA)" },
  { name: "BANK OF TANZANIA" },
  { name: "BARCLAYS BANK OF TANZANIA" },
  { name: "CANARA BANK OF TANZANIA" },
  { name: "CHINA COMMERCIAL BANK" },
  { name: "CITIBANK" },
  { name: "COMMERCIAL BANK OF AFRICA (TANZANIA)" },
  { name: "CRDB BANK" },
  { name: "DIAMOND TRUST BANK TANZANIA" },
  { name: "ECOBANK" },
  { name: "ECO BANK" },
  { name: "EFATHA BANK LIMITED" },
  { name: "EQUITY BANK (TANZANIA)" },
  { name: "EXIM BANK (TANZANIA)" },
  { name: "FINCA MICROFINANCE BANK LIMITED" },
  { name: "FIRST NATIONAL BANK OF TANZANIA" },
  { name: "GUARANTY TRUST BANK" },
  { name: "HABIB AFRICAN BANK" },
  { name: "I&M BANK TANZANIA" },
  { name: "INTERNATIONAL COMMERCIAL BANK" },
  { name: "KCB BANK TANZANIA" },
  { name: "KILIMANJARO CO-OPERATIVE BANK" },
  { name: "MAENDELEO BANK" },
  { name: "MERU COMMUNITY BANK LTD" },
  { name: "MKOMBOZI NATIONAL BANK" },
  { name: "MUCOBA BANK PLC" },
  { name: "MWALIMU COMMERCIAL BANK" },
  { name: "MWANGA COMMUNITY BANK" },
  { name: "NATIONAL MICROFINANCE BANK" },
  { name: "NBC LIMITED" },
  { name: "NIC BANK TANZANIA" },
  { name: "PEOPLE'S BANK OF ZANZIBAR" },
  { name: "STANBIC BANK TANZANIA LIMITED" },
  { name: "STANDARD CHARTERED BANK" },
  { name: "TANZANIA AGRICULTURAL DEVELOPMENT" },
  { name: "TANZANIA POSTAL BANK" },
  { name: "TANZANIA WOMEN'S BANK LTD" },
  { name: "TIB CORPORATE BANK" },
  { name: "TWIGA BANCORP LIMITED" },
  { name: "UBL BANK TANZANIA LIMITED" },
  { name: "UCHUMI COMMERCIAL BANK" },
  { name: "UNITED BANK FOR AFRICA" },
  { name: "ABC CAPITAL BANK LIMITED" },
  { name: "BANK OF AFRICA - UGANDA LIMITED" },
  { name: "BARCLAYS BANK OF UGANDA LIMITED" },
  { name: "BANK OF BARODA (UGANDA) LIMITED" },
  { name: "BANK OF INDIA (UGANDA) LIMITED" },
  { name: "CAIRO INTERNATIONAL BANK LIMITED" },
  { name: "CENTERARY RURAL DEVELOPMENT BANK" },
  { name: "CITIBANK UGANDA LIMITED" },
  { name: "COMMERCIAL BANK OF AFRICA UGANDA" },
  { name: "DFCU BANK LIMITED" },
  { name: "DIAMOND TRUST BANK UGANDA LIMITED" },
  { name: "EAST AFRICAN DEVELOPMENT BANK" },
  { name: "ECOBANK UGANDA LIMITED" },
  { name: "EQUITY BANK UGANDA LIMITED" },
  { name: "EXIM BANK (UGANDA) LIMITED" },
  { name: "FINCA BANK UGANDA" },
  { name: "FINANCE TRUST BANK LTD" },
  { name: "GUARANTY TRUST BANK LTD" },
  { name: "HOUSING FINANCE BANK LTD" },
  { name: "KCB BANK UGANDA LTD" },
  { name: "MERCANTILE CREDIT BANK" },
  { name: "NC BANK UGANDA BANK" },
  { name: "ORIENT BANK" },
  { name: "OPPORTUNITY BANK UGANDA LTD" },
  { name: "POSTBANK UGANDA" },
  { name: "PRIDE MICROFINANCE BANK" },
  { name: "STANBIC BANK UGANDA LIMITED" },
  { name: "STANDARD CHARTERED BANK UGANDA" },
  { name: "TOP FINANCE BANK UGANDA LIMITED" },
  { name: "TROPICAL BANK LIMITED" },
  { name: "UNITED BANK FOR AFRICA (UGANDA)" }
]