export const countrylist = [
    {
      countryCode: "AF",
      countryName: "Afghanistan",
      currency: "AFN",
      currencySymbol: "؋",
      nationality: "Afghan",
      dialCode: "93",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/afghanistan.svg",
      operatingCountry: false,
      countryCode3Chars: "AFG"
    },
    {
      countryCode: "AX",
      countryName: "Åland Islands",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Ålandish",
      dialCode: "358",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/europe.svg",
      operatingCountry: false,
      countryCode3Chars: "ALA"
    },
    {
      countryCode: "AL",
      countryName: "Albania",
      currency: "ALL",
      currencySymbol: "L",
      nationality: "Albanian",
      dialCode: "355",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/albania.svg",
      operatingCountry: false,
      countryCode3Chars: "ALB"
    },
    {
      countryCode: "DZ",
      countryName: "Algeria",
      currency: "DZD",
      currencySymbol: "د.ج",
      nationality: "Algerian",
      dialCode: "213",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/algeria.svg",
      operatingCountry: false,
      countryCode3Chars: "DZA"
    },
    {
      countryCode: "AS",
      countryName: "American Samoa",
      currency: "USD",
      currencySymbol: "$",
      nationality: "American Samoan",
      dialCode: "1684",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-states-of-america.svg",
      operatingCountry: false,
      countryCode3Chars: "ASM"
    },
    {
      countryCode: "AD",
      countryName: "Andorra",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Andorran",
      dialCode: "376",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/europe.svg",
      operatingCountry: false,
      countryCode3Chars: "AND"
    },
    {
      countryCode: "AO",
      countryName: "Angola",
      currency: "AOA",
      currencySymbol: "Kz",
      nationality: "Angolan",
      dialCode: "244",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/angola.svg",
      operatingCountry: false,
      countryCode3Chars: "AGO"
    },
    {
      countryCode: "AI",
      countryName: "Anguilla",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Anguillian",
      dialCode: "1264",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/anguilla.svg",
      operatingCountry: false,
      countryCode3Chars: "AIA"
    },
    {
      countryCode: "AQ",
      countryName: "Antarctica",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "",
      dialCode: "672",
      flagPath: "https://restcountries.eu/data/ata.svg",
      operatingCountry: false,
      countryCode3Chars: "ATA"
    },
    {
      countryCode: "AG",
      countryName: "Antigua and Barbuda",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Antiguan, Barbudan",
      dialCode: "1268",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/antigua-and-barbuda.svg",
      operatingCountry: false,
      countryCode3Chars: "ATG"
    },
    {
      countryCode: "AR",
      countryName: "Argentina",
      currency: "ARS",
      currencySymbol: "$",
      nationality: "Argentinean",
      dialCode: "54",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/argentina.svg",
      operatingCountry: false,
      countryCode3Chars: "ARG"
    },
    {
      countryCode: "AM",
      countryName: "Armenia",
      currency: "AMD",
      currencySymbol: null,
      nationality: "Armenian",
      dialCode: "374",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/armenia.svg",
      operatingCountry: false,
      countryCode3Chars: "ARM"
    },
    {
      countryCode: "AW",
      countryName: "Aruba",
      currency: "AWG",
      currencySymbol: "ƒ",
      nationality: "Aruban",
      dialCode: "297",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/aruba.svg",
      operatingCountry: false,
      countryCode3Chars: "ABW"
    },
    {
      countryCode: "AU",
      countryName: "Australia",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Australian",
      dialCode: "61",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/australia.svg",
      operatingCountry: false,
      countryCode3Chars: "AUS"
    },
    {
      countryCode: "AT",
      countryName: "Austria",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Austrian",
      dialCode: "43",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/austria.svg",
      operatingCountry: false,
      countryCode3Chars: "AUT"
    },
    {
      countryCode: "AZ",
      countryName: "Azerbaijan",
      currency: "AZN",
      currencySymbol: null,
      nationality: "Azerbaijani",
      dialCode: "994",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/azerbaijan.svg",
      operatingCountry: false,
      countryCode3Chars: "AZE"
    },
    {
      countryCode: "BS",
      countryName: "Bahamas",
      currency: "BSD",
      currencySymbol: "$",
      nationality: "Bahamian",
      dialCode: "1242",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bahamas.svg",
      operatingCountry: false,
      countryCode3Chars: "BHS"
    },
    {
      countryCode: "BH",
      countryName: "Bahrain",
      currency: "BHD",
      currencySymbol: ".د.ب",
      nationality: "Bahraini",
      dialCode: "973",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bahrain.svg",
      operatingCountry: false,
      countryCode3Chars: "BHR"
    },
    {
      countryCode: "BD",
      countryName: "Bangladesh",
      currency: "BDT",
      currencySymbol: "৳",
      nationality: "Bangladeshi",
      dialCode: "880",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bangladesh.svg",
      operatingCountry: false,
      countryCode3Chars: "BGD"
    },
    {
      countryCode: "BB",
      countryName: "Barbados",
      currency: "BBD",
      currencySymbol: "$",
      nationality: "Barbadian",
      dialCode: "1246",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/barbados.svg",
      operatingCountry: false,
      countryCode3Chars: "BRB"
    },
    {
      countryCode: "BY",
      countryName: "Belarus",
      currency: "BYN",
      currencySymbol: "Br",
      nationality: "Belarusian",
      dialCode: "375",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/belarus.svg",
      operatingCountry: false,
      countryCode3Chars: "BLR"
    },
    {
      countryCode: "BE",
      countryName: "Belgium",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Belgian",
      dialCode: "32",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/belgium.svg",
      operatingCountry: false,
      countryCode3Chars: "BEL"
    },
    {
      countryCode: "BZ",
      countryName: "Belize",
      currency: "BZD",
      currencySymbol: "$",
      nationality: "Belizean",
      dialCode: "501",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/belize.svg",
      operatingCountry: false,
      countryCode3Chars: "BLZ"
    },
    {
      countryCode: "BJ",
      countryName: "Benin",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Beninese",
      dialCode: "229",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/benin.svg",
      operatingCountry: false,
      countryCode3Chars: "BEN"
    },
    {
      countryCode: "BM",
      countryName: "Bermuda",
      currency: "BMD",
      currencySymbol: "$",
      nationality: "Bermudian",
      dialCode: "1441",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bermuda.svg",
      operatingCountry: false,
      countryCode3Chars: "BMU"
    },
    {
      countryCode: "BT",
      countryName: "Bhutan",
      currency: "BTN",
      currencySymbol: "Nu.",
      nationality: "Bhutanese",
      dialCode: "975",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bhutan.svg",
      operatingCountry: false,
      countryCode3Chars: "BTN"
    },
    {
      countryCode: "BO",
      countryName: "Bolivia (Plurinational State of)",
      currency: "BOB",
      currencySymbol: "Bs.",
      nationality: "Bolivian",
      dialCode: "591",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bolivia.svg",
      operatingCountry: false,
      countryCode3Chars: "BOL"
    },
    {
      countryCode: "BQ",
      countryName: "Bonaire, Sint Eustatius and Saba",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Dutch",
      dialCode: "5997",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bonaire.svg",
      operatingCountry: false,
      countryCode3Chars: "BES"
    },
    {
      countryCode: "BA",
      countryName: "Bosnia and Herzegovina",
      currency: "BAM",
      currencySymbol: null,
      nationality: "Bosnian, Herzegovinian",
      dialCode: "387",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bosnia-and-herzegovina.svg",
      operatingCountry: false,
      countryCode3Chars: "BIH"
    },
    {
      countryCode: "BW",
      countryName: "Botswana",
      currency: "BWP",
      currencySymbol: "P",
      nationality: "Motswana",
      dialCode: "267",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/botswana.svg",
      operatingCountry: false,
      countryCode3Chars: "BWA"
    },
    {
      countryCode: "BV",
      countryName: "Bouvet Island",
      currency: "NOK",
      currencySymbol: "kr",
      nationality: "",
      dialCode: "",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/norway.svg",
      operatingCountry: false,
      countryCode3Chars: "BVT"
    },
    {
      countryCode: "BR",
      countryName: "Brazil",
      currency: "BRL",
      currencySymbol: "R$",
      nationality: "Brazilian",
      dialCode: "55",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/brazil.svg",
      operatingCountry: false,
      countryCode3Chars: "BRA"
    },
    {
      countryCode: "IO",
      countryName: "British Indian Ocean Territory",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Indian",
      dialCode: "246",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/british-indian-ocean-territory.svg",
      operatingCountry: false,
      countryCode3Chars: "IOT"
    },
    {
      countryCode: "UM",
      countryName: "United States Minor Outlying Islands",
      currency: "USD",
      currencySymbol: "$",
      nationality: "American",
      dialCode: "",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-states-of-america.svg",
      operatingCountry: false,
      countryCode3Chars: "UMI"
    },
    {
      countryCode: "VG",
      countryName: "Virgin Islands (British)",
      currency: null,
      currencySymbol: "$",
      nationality: "Virgin Islander",
      dialCode: "1284",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/british-virgin-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "VGB"
    },
    {
      countryCode: "VI",
      countryName: "Virgin Islands (U.S.)",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Virgin Islander",
      dialCode: "1 340",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/virgin-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "VIR"
    },
    {
      countryCode: "BN",
      countryName: "Brunei Darussalam",
      currency: "BND",
      currencySymbol: "$",
      nationality: "Bruneian",
      dialCode: "673",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/brunei.svg",
      operatingCountry: false,
      countryCode3Chars: "BRN"
    },
    {
      countryCode: "BG",
      countryName: "Bulgaria",
      currency: "BGN",
      currencySymbol: "лв",
      nationality: "Bulgarian",
      dialCode: "359",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/bulgaria.svg",
      operatingCountry: false,
      countryCode3Chars: "BGR"
    },
    {
      countryCode: "BF",
      countryName: "Burkina Faso",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Burkinabe",
      dialCode: "226",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/burkina-faso.svg",
      operatingCountry: false,
      countryCode3Chars: "BFA"
    },
    {
      countryCode: "BI",
      countryName: "Burundi",
      currency: "BIF",
      currencySymbol: "Fr",
      nationality: "Burundian",
      dialCode: "257",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/burundi.svg",
      operatingCountry: false,
      countryCode3Chars: "BDI"
    },
    {
      countryCode: "KH",
      countryName: "Cambodia",
      currency: "KHR",
      currencySymbol: "៛",
      nationality: "Cambodian",
      dialCode: "855",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cambodia.svg",
      operatingCountry: false,
      countryCode3Chars: "KHM"
    },
    {
      countryCode: "CM",
      countryName: "Cameroon",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Cameroonian",
      dialCode: "237",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cameroon.svg",
      operatingCountry: false,
      countryCode3Chars: "CMR"
    },
    {
      countryCode: "CA",
      countryName: "Canada",
      currency: "CAD",
      currencySymbol: "$",
      nationality: "Canadian",
      dialCode: "1",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/canada.svg",
      operatingCountry: false,
      countryCode3Chars: "CAN"
    },
    {
      countryCode: "CV",
      countryName: "Cabo Verde",
      currency: "CVE",
      currencySymbol: "Esc",
      nationality: "Cape Verdian",
      dialCode: "238",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cape-verde.svg",
      operatingCountry: false,
      countryCode3Chars: "CPV"
    },
    {
      countryCode: "KY",
      countryName: "Cayman Islands",
      currency: "KYD",
      currencySymbol: "$",
      nationality: "Caymanian",
      dialCode: "1345",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cayman-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "CYM"
    },
    {
      countryCode: "CF",
      countryName: "Central African Republic",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Central African",
      dialCode: "236",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/central-african-republic.svg",
      operatingCountry: false,
      countryCode3Chars: "CAF"
    },
    {
      countryCode: "TD",
      countryName: "Chad",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Chadian",
      dialCode: "235",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/chad.svg",
      operatingCountry: false,
      countryCode3Chars: "TCD"
    },
    {
      countryCode: "CL",
      countryName: "Chile",
      currency: "CLP",
      currencySymbol: "$",
      nationality: "Chilean",
      dialCode: "56",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/chile.svg",
      operatingCountry: false,
      countryCode3Chars: "CHL"
    },
    {
      countryCode: "CN",
      countryName: "China",
      currency: "CNY",
      currencySymbol: "¥",
      nationality: "Chinese",
      dialCode: "86",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/china.svg",
      operatingCountry: false,
      countryCode3Chars: "CHN"
    },
    {
      countryCode: "CX",
      countryName: "Christmas Island",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Christmas Island",
      dialCode: "61",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/christmas-island.svg",
      operatingCountry: false,
      countryCode3Chars: "CXR"
    },
    {
      countryCode: "CC",
      countryName: "Cocos (Keeling) Islands",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Cocos Islander",
      dialCode: "61",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cocos-island.svg",
      operatingCountry: false,
      countryCode3Chars: "CCK"
    },
    {
      countryCode: "CO",
      countryName: "Colombia",
      currency: "COP",
      currencySymbol: "$",
      nationality: "Colombian",
      dialCode: "57",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/colombia.svg",
      operatingCountry: false,
      countryCode3Chars: "COL"
    },
    {
      countryCode: "KM",
      countryName: "Comoros",
      currency: "KMF",
      currencySymbol: "Fr",
      nationality: "Comoran",
      dialCode: "269",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/comoros.svg",
      operatingCountry: false,
      countryCode3Chars: "COM"
    },
    {
      countryCode: "CG",
      countryName: "Congo",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Congolese",
      dialCode: "242",
      flagPath: "https://restcountries.eu/data/cog.svg",
      operatingCountry: false,
      countryCode3Chars: "COG"
    },
    {
      countryCode: "CD",
      countryName: "Congo (Democratic Republic of the)",
      currency: "CDF",
      currencySymbol: "Fr",
      nationality: "Congolese",
      dialCode: "243",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/democratic-republic-of-congo.svg",
      operatingCountry: true,
      countryCode3Chars: "COD"
    },
    {
      countryCode: "CK",
      countryName: "Cook Islands",
      currency: "NZD",
      currencySymbol: "$",
      nationality: "Cook Islander",
      dialCode: "682",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cook-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "COK"
    },
    {
      countryCode: "CR",
      countryName: "Costa Rica",
      currency: "CRC",
      currencySymbol: "₡",
      nationality: "Costa Rican",
      dialCode: "506",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/costa-rica.svg",
      operatingCountry: false,
      countryCode3Chars: "CRI"
    },
    {
      countryCode: "HR",
      countryName: "Croatia",
      currency: "HRK",
      currencySymbol: "kn",
      nationality: "Croatian",
      dialCode: "385",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/croatia.svg",
      operatingCountry: false,
      countryCode3Chars: "HRV"
    },
    {
      countryCode: "CU",
      countryName: "Cuba",
      currency: "CUC",
      currencySymbol: "$",
      nationality: "Cuban",
      dialCode: "53",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cuba.svg",
      operatingCountry: false,
      countryCode3Chars: "CUB"
    },
    {
      countryCode: "CW",
      countryName: "Curaçao",
      currency: "ANG",
      currencySymbol: "ƒ",
      nationality: "Dutch",
      dialCode: "599",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/curacao.svg",
      operatingCountry: false,
      countryCode3Chars: "CUW"
    },
    {
      countryCode: "CY",
      countryName: "Cyprus",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Cypriot",
      dialCode: "357",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/cyprus.svg",
      operatingCountry: false,
      countryCode3Chars: "CYP"
    },
    {
      countryCode: "CZ",
      countryName: "Czech Republic",
      currency: "CZK",
      currencySymbol: "Kč",
      nationality: "Czech",
      dialCode: "420",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/czech-republic.svg",
      operatingCountry: false,
      countryCode3Chars: "CZE"
    },
    {
      countryCode: "DK",
      countryName: "Denmark",
      currency: "DKK",
      currencySymbol: "kr",
      nationality: "Danish",
      dialCode: "45",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/denmark.svg",
      operatingCountry: false,
      countryCode3Chars: "DNK"
    },
    {
      countryCode: "DJ",
      countryName: "Djibouti",
      currency: "DJF",
      currencySymbol: "Fr",
      nationality: "Djibouti",
      dialCode: "253",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/djibouti.svg",
      operatingCountry: false,
      countryCode3Chars: "DJI"
    },
    {
      countryCode: "DM",
      countryName: "Dominica",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Dominican",
      dialCode: "1767",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/dominica.svg",
      operatingCountry: false,
      countryCode3Chars: "DMA"
    },
    {
      countryCode: "DO",
      countryName: "Dominican Republic",
      currency: "DOP",
      currencySymbol: "$",
      nationality: "Dominican",
      dialCode: "1809",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/dominican-republic.svg",
      operatingCountry: false,
      countryCode3Chars: "DOM"
    },
    {
      countryCode: "EC",
      countryName: "Ecuador",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Ecuadorean",
      dialCode: "593",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ecuador.svg",
      operatingCountry: false,
      countryCode3Chars: "ECU"
    },
    {
      countryCode: "EG",
      countryName: "Egypt",
      currency: "EGP",
      currencySymbol: "£",
      nationality: "Egyptian",
      dialCode: "20",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/egypt.svg",
      operatingCountry: false,
      countryCode3Chars: "EGY"
    },
    {
      countryCode: "SV",
      countryName: "El Salvador",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Salvadoran",
      dialCode: "503",
      flagPath: "https://restcountries.eu/data/slv.svg",
      operatingCountry: false,
      countryCode3Chars: "SLV"
    },
    {
      countryCode: "GQ",
      countryName: "Equatorial Guinea",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Equatorial Guinean",
      dialCode: "240",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/equatorial-guinea.svg",
      operatingCountry: false,
      countryCode3Chars: "GNQ"
    },
    {
      countryCode: "ER",
      countryName: "Eritrea",
      currency: "ERN",
      currencySymbol: "Nfk",
      nationality: "Eritrean",
      dialCode: "291",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/eritrea.svg",
      operatingCountry: false,
      countryCode3Chars: "ERI"
    },
    {
      countryCode: "EE",
      countryName: "Estonia",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Estonian",
      dialCode: "372",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/estonia.svg",
      operatingCountry: false,
      countryCode3Chars: "EST"
    },
    {
      countryCode: "ET",
      countryName: "Ethiopia",
      currency: "ETB",
      currencySymbol: "Br",
      nationality: "Ethiopian",
      dialCode: "251",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ethiopia.svg",
      operatingCountry: false,
      countryCode3Chars: "ETH"
    },
    {
      countryCode: "FK",
      countryName: "Falkland Islands (Malvinas)",
      currency: "FKP",
      currencySymbol: "£",
      nationality: "Falkland Islander",
      dialCode: "500",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/falkland-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "FLK"
    },
    {
      countryCode: "FO",
      countryName: "Faroe Islands",
      currency: "DKK",
      currencySymbol: "kr",
      nationality: "Faroese",
      dialCode: "298",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/faroe-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "FRO"
    },
    {
      countryCode: "FJ",
      countryName: "Fiji",
      currency: "FJD",
      currencySymbol: "$",
      nationality: "Fijian",
      dialCode: "679",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/fiji.svg",
      operatingCountry: false,
      countryCode3Chars: "FJI"
    },
    {
      countryCode: "FI",
      countryName: "Finland",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Finnish",
      dialCode: "358",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/finland.svg",
      operatingCountry: false,
      countryCode3Chars: "FIN"
    },
    {
      countryCode: "FR",
      countryName: "France",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "33",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/france.svg",
      operatingCountry: false,
      countryCode3Chars: "FRA"
    },
    {
      countryCode: "GF",
      countryName: "French Guiana",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "",
      dialCode: "594",
      flagPath: "https://restcountries.eu/data/guf.svg",
      operatingCountry: false,
      countryCode3Chars: "GUF"
    },
    {
      countryCode: "PF",
      countryName: "French Polynesia",
      currency: "XPF",
      currencySymbol: "Fr",
      nationality: "French Polynesian",
      dialCode: "689",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/french-polynesia.svg",
      operatingCountry: false,
      countryCode3Chars: "PYF"
    },
    {
      countryCode: "TF",
      countryName: "French Southern Territories",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "",
      flagPath: "https://restcountries.eu/data/atf.svg",
      operatingCountry: false,
      countryCode3Chars: "ATF"
    },
    {
      countryCode: "GA",
      countryName: "Gabon",
      currency: "XAF",
      currencySymbol: "Fr",
      nationality: "Gabonese",
      dialCode: "241",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/gabon.svg",
      operatingCountry: false,
      countryCode3Chars: "GAB"
    },
    {
      countryCode: "GM",
      countryName: "Gambia",
      currency: "GMD",
      currencySymbol: "D",
      nationality: "Gambian",
      dialCode: "220",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/gambia.svg",
      operatingCountry: false,
      countryCode3Chars: "GMB"
    },
    {
      countryCode: "GE",
      countryName: "Georgia",
      currency: "GEL",
      currencySymbol: "ლ",
      nationality: "Georgian",
      dialCode: "995",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/georgia.svg",
      operatingCountry: false,
      countryCode3Chars: "GEO"
    },
    {
      countryCode: "DE",
      countryName: "Germany",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "German",
      dialCode: "49",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/germany.svg",
      operatingCountry: false,
      countryCode3Chars: "DEU"
    },
    {
      countryCode: "GH",
      countryName: "Ghana",
      currency: "GHS",
      currencySymbol: "₵",
      nationality: "Ghanaian",
      dialCode: "233",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ghana.svg",
      operatingCountry: false,
      countryCode3Chars: "GHA"
    },
    {
      countryCode: "GI",
      countryName: "Gibraltar",
      currency: "GIP",
      currencySymbol: "£",
      nationality: "Gibraltar",
      dialCode: "350",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/gibraltar.svg",
      operatingCountry: false,
      countryCode3Chars: "GIB"
    },
    {
      countryCode: "GR",
      countryName: "Greece",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Greek",
      dialCode: "30",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/greece.svg",
      operatingCountry: false,
      countryCode3Chars: "GRC"
    },
    {
      countryCode: "GL",
      countryName: "Greenland",
      currency: "DKK",
      currencySymbol: "kr",
      nationality: "Greenlandic",
      dialCode: "299",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/greenland.svg",
      operatingCountry: false,
      countryCode3Chars: "GRL"
    },
    {
      countryCode: "GD",
      countryName: "Grenada",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Grenadian",
      dialCode: "1473",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/grenada.svg",
      operatingCountry: false,
      countryCode3Chars: "GRD"
    },
    {
      countryCode: "GP",
      countryName: "Guadeloupe",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Guadeloupian",
      dialCode: "590",
      flagPath: "https://restcountries.eu/data/glp.svg",
      operatingCountry: false,
      countryCode3Chars: "GLP"
    },
    {
      countryCode: "GU",
      countryName: "Guam",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Guamanian",
      dialCode: "1671",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/guam.svg",
      operatingCountry: false,
      countryCode3Chars: "GUM"
    },
    {
      countryCode: "GT",
      countryName: "Guatemala",
      currency: "GTQ",
      currencySymbol: "Q",
      nationality: "Guatemalan",
      dialCode: "502",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/guatemala.svg",
      operatingCountry: false,
      countryCode3Chars: "GTM"
    },
    {
      countryCode: "GG",
      countryName: "Guernsey",
      currency: "GBP",
      currencySymbol: "£",
      nationality: "Channel Islander",
      dialCode: "44",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-kingdom.svg",
      operatingCountry: false,
      countryCode3Chars: "GGY"
    },
    {
      countryCode: "GN",
      countryName: "Guinea",
      currency: "GNF",
      currencySymbol: "Fr",
      nationality: "Guinean",
      dialCode: "224",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/guinea.svg",
      operatingCountry: false,
      countryCode3Chars: "GIN"
    },
    {
      countryCode: "GW",
      countryName: "Guinea-Bissau",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Guinea-Bissauan",
      dialCode: "245",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/guinea-bissau.svg",
      operatingCountry: false,
      countryCode3Chars: "GNB"
    },
    {
      countryCode: "GY",
      countryName: "Guyana",
      currency: "GYD",
      currencySymbol: "$",
      nationality: "Guyanese",
      dialCode: "592",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/guyana.svg",
      operatingCountry: false,
      countryCode3Chars: "GUY"
    },
    {
      countryCode: "HT",
      countryName: "Haiti",
      currency: "HTG",
      currencySymbol: "G",
      nationality: "Haitian",
      dialCode: "509",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/haiti.svg",
      operatingCountry: false,
      countryCode3Chars: "HTI"
    },
    {
      countryCode: "HM",
      countryName: "Heard Island and McDonald Islands",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Heard and McDonald Islander",
      dialCode: "",
      flagPath: "https://restcountries.eu/data/hmd.svg",
      operatingCountry: false,
      countryCode3Chars: "HMD"
    },
    {
      countryCode: "VA",
      countryName: "Holy See",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "",
      dialCode: "379",
      flagPath: "https://restcountries.eu/data/vat.svg",
      operatingCountry: false,
      countryCode3Chars: "VAT"
    },
    {
      countryCode: "HN",
      countryName: "Honduras",
      currency: "HNL",
      currencySymbol: "L",
      nationality: "Honduran",
      dialCode: "504",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/honduras.svg",
      operatingCountry: false,
      countryCode3Chars: "HND"
    },
    {
      countryCode: "HK",
      countryName: "Hong Kong",
      currency: "HKD",
      currencySymbol: "$",
      nationality: "Chinese",
      dialCode: "852",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/hong-kong.svg",
      operatingCountry: false,
      countryCode3Chars: "HKG"
    },
    {
      countryCode: "HU",
      countryName: "Hungary",
      currency: "HUF",
      currencySymbol: "Ft",
      nationality: "Hungarian",
      dialCode: "36",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/hungary.svg",
      operatingCountry: false,
      countryCode3Chars: "HUN"
    },
    {
      countryCode: "IS",
      countryName: "Iceland",
      currency: "ISK",
      currencySymbol: "kr",
      nationality: "Icelander",
      dialCode: "354",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/iceland.svg",
      operatingCountry: false,
      countryCode3Chars: "ISL"
    },
    {
      countryCode: "IN",
      countryName: "India",
      currency: "INR",
      currencySymbol: "₹",
      nationality: "Indian",
      dialCode: "91",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/india.svg",
      operatingCountry: false,
      countryCode3Chars: "IND"
    },
    {
      countryCode: "ID",
      countryName: "Indonesia",
      currency: "IDR",
      currencySymbol: "Rp",
      nationality: "Indonesian",
      dialCode: "62",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/indonesia.svg",
      operatingCountry: false,
      countryCode3Chars: "IDN"
    },
    {
      countryCode: "CI",
      countryName: "Côte d'Ivoire",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Ivorian",
      dialCode: "225",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ivory-coast.svg",
      operatingCountry: false,
      countryCode3Chars: "CIV"
    },
    {
      countryCode: "IR",
      countryName: "Iran (Islamic Republic of)",
      currency: "IRR",
      currencySymbol: "﷼",
      nationality: "Iranian",
      dialCode: "98",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/iran.svg",
      operatingCountry: false,
      countryCode3Chars: "IRN"
    },
    {
      countryCode: "IQ",
      countryName: "Iraq",
      currency: "IQD",
      currencySymbol: "ع.د",
      nationality: "Iraqi",
      dialCode: "964",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/iraq.svg",
      operatingCountry: false,
      countryCode3Chars: "IRQ"
    },
    {
      countryCode: "IE",
      countryName: "Ireland",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Irish",
      dialCode: "353",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ireland.svg",
      operatingCountry: false,
      countryCode3Chars: "IRL"
    },
    {
      countryCode: "IM",
      countryName: "Isle of Man",
      currency: "GBP",
      currencySymbol: "£",
      nationality: "Manx",
      dialCode: "44",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/isle-of-man.svg",
      operatingCountry: false,
      countryCode3Chars: "IMN"
    },
    {
      countryCode: "IL",
      countryName: "Israel",
      currency: "ILS",
      currencySymbol: "₪",
      nationality: "Israeli",
      dialCode: "972",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/israel.svg",
      operatingCountry: false,
      countryCode3Chars: "ISR"
    },
    {
      countryCode: "IT",
      countryName: "Italy",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Italian",
      dialCode: "39",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/italy.svg",
      operatingCountry: false,
      countryCode3Chars: "ITA"
    },
    {
      countryCode: "JM",
      countryName: "Jamaica",
      currency: "JMD",
      currencySymbol: "$",
      nationality: "Jamaican",
      dialCode: "1876",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/jamaica.svg",
      operatingCountry: false,
      countryCode3Chars: "JAM"
    },
    {
      countryCode: "JP",
      countryName: "Japan",
      currency: "JPY",
      currencySymbol: "¥",
      nationality: "Japanese",
      dialCode: "81",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/japan.svg",
      operatingCountry: false,
      countryCode3Chars: "JPN"
    },
    {
      countryCode: "JE",
      countryName: "Jersey",
      currency: "GBP",
      currencySymbol: "£",
      nationality: "Channel Islander",
      dialCode: "44",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/jersey.svg",
      operatingCountry: false,
      countryCode3Chars: "JEY"
    },
    {
      countryCode: "JO",
      countryName: "Jordan",
      currency: "JOD",
      currencySymbol: "د.ا",
      nationality: "Jordanian",
      dialCode: "962",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/jordan.svg",
      operatingCountry: false,
      countryCode3Chars: "JOR"
    },
    {
      countryCode: "KZ",
      countryName: "Kazakhstan",
      currency: "KZT",
      currencySymbol: null,
      nationality: "Kazakhstani",
      dialCode: "76",
      flagPath: "https://restcountries.eu/data/kaz.svg",
      operatingCountry: false,
      countryCode3Chars: "KAZ"
    },
    {
      countryCode: "KE",
      countryName: "Kenya",
      currency: "KES",
      currencySymbol: "Sh",
      nationality: "Kenyan",
      dialCode: "254",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/kenya.svg",
      operatingCountry: true,
      countryCode3Chars: "KEN"
    },
    {
      countryCode: "KI",
      countryName: "Kiribati",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "I-Kiribati",
      dialCode: "686",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/kiribati.svg",
      operatingCountry: false,
      countryCode3Chars: "KIR"
    },
    {
      countryCode: "KW",
      countryName: "Kuwait",
      currency: "KWD",
      currencySymbol: "د.ك",
      nationality: "Kuwaiti",
      dialCode: "965",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/kuwait.svg",
      operatingCountry: false,
      countryCode3Chars: "KWT"
    },
    {
      countryCode: "KG",
      countryName: "Kyrgyzstan",
      currency: "KGS",
      currencySymbol: "с",
      nationality: "Kirghiz",
      dialCode: "996",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/kyrgyzstan.svg",
      operatingCountry: false,
      countryCode3Chars: "KGZ"
    },
    {
      countryCode: "LA",
      countryName: "Lao People's Democratic Republic",
      currency: "LAK",
      currencySymbol: "₭",
      nationality: "Laotian",
      dialCode: "856",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/laos.svg",
      operatingCountry: false,
      countryCode3Chars: "LAO"
    },
    {
      countryCode: "LV",
      countryName: "Latvia",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Latvian",
      dialCode: "371",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/latvia.svg",
      operatingCountry: false,
      countryCode3Chars: "LVA"
    },
    {
      countryCode: "LB",
      countryName: "Lebanon",
      currency: "LBP",
      currencySymbol: "ل.ل",
      nationality: "Lebanese",
      dialCode: "961",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/lebanon.svg",
      operatingCountry: false,
      countryCode3Chars: "LBN"
    },
    {
      countryCode: "LS",
      countryName: "Lesotho",
      currency: "LSL",
      currencySymbol: "L",
      nationality: "Mosotho",
      dialCode: "266",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/lesotho.svg",
      operatingCountry: false,
      countryCode3Chars: "LSO"
    },
    {
      countryCode: "LR",
      countryName: "Liberia",
      currency: "LRD",
      currencySymbol: "$",
      nationality: "Liberian",
      dialCode: "231",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/liberia.svg",
      operatingCountry: false,
      countryCode3Chars: "LBR"
    },
    {
      countryCode: "LY",
      countryName: "Libya",
      currency: "LYD",
      currencySymbol: "ل.د",
      nationality: "Libyan",
      dialCode: "218",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/libya.svg",
      operatingCountry: false,
      countryCode3Chars: "LBY"
    },
    {
      countryCode: "LI",
      countryName: "Liechtenstein",
      currency: "CHF",
      currencySymbol: "Fr",
      nationality: "Liechtensteiner",
      dialCode: "423",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/liechtenstein.svg",
      operatingCountry: false,
      countryCode3Chars: "LIE"
    },
    {
      countryCode: "LT",
      countryName: "Lithuania",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Lithuanian",
      dialCode: "370",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/lithuania.svg",
      operatingCountry: false,
      countryCode3Chars: "LTU"
    },
    {
      countryCode: "LU",
      countryName: "Luxembourg",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Luxembourger",
      dialCode: "352",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/luxembourg.svg",
      operatingCountry: false,
      countryCode3Chars: "LUX"
    },
    {
      countryCode: "MO",
      countryName: "Macao",
      currency: "MOP",
      currencySymbol: "P",
      nationality: "Chinese",
      dialCode: "853",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/macao.svg",
      operatingCountry: false,
      countryCode3Chars: "MAC"
    },
    {
      countryCode: "MK",
      countryName: "Macedonia (the former Yugoslav Republic of)",
      currency: "MKD",
      currencySymbol: "ден",
      nationality: "Macedonian",
      dialCode: "389",
      flagPath: "https://restcountries.eu/data/mkd.svg",
      operatingCountry: false,
      countryCode3Chars: "MKD"
    },
    {
      countryCode: "MG",
      countryName: "Madagascar",
      currency: "MGA",
      currencySymbol: "Ar",
      nationality: "Malagasy",
      dialCode: "261",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/madagascar.svg",
      operatingCountry: false,
      countryCode3Chars: "MDG"
    },
    {
      countryCode: "MW",
      countryName: "Malawi",
      currency: "MWK",
      currencySymbol: "MK",
      nationality: "Malawian",
      dialCode: "265",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/malawi.svg",
      operatingCountry: false,
      countryCode3Chars: "MWI"
    },
    {
      countryCode: "MY",
      countryName: "Malaysia",
      currency: "MYR",
      currencySymbol: "RM",
      nationality: "Malaysian",
      dialCode: "60",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/malaysia.svg",
      operatingCountry: false,
      countryCode3Chars: "MYS"
    },
    {
      countryCode: "MV",
      countryName: "Maldives",
      currency: "MVR",
      currencySymbol: ".ރ",
      nationality: "Maldivan",
      dialCode: "960",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/maldives.svg",
      operatingCountry: false,
      countryCode3Chars: "MDV"
    },
    {
      countryCode: "ML",
      countryName: "Mali",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Malian",
      dialCode: "223",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mali.svg",
      operatingCountry: false,
      countryCode3Chars: "MLI"
    },
    {
      countryCode: "MT",
      countryName: "Malta",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Maltese",
      dialCode: "356",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/malta.svg",
      operatingCountry: false,
      countryCode3Chars: "MLT"
    },
    {
      countryCode: "MH",
      countryName: "Marshall Islands",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Marshallese",
      dialCode: "692",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/marshall-island.svg",
      operatingCountry: false,
      countryCode3Chars: "MHL"
    },
    {
      countryCode: "MQ",
      countryName: "Martinique",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "596",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/martinique.svg",
      operatingCountry: false,
      countryCode3Chars: "MTQ"
    },
    {
      countryCode: "MR",
      countryName: "Mauritania",
      currency: "MRO",
      currencySymbol: "UM",
      nationality: "Mauritanian",
      dialCode: "222",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mauritania.svg",
      operatingCountry: false,
      countryCode3Chars: "MRT"
    },
    {
      countryCode: "MU",
      countryName: "Mauritius",
      currency: "MUR",
      currencySymbol: "₨",
      nationality: "Mauritian",
      dialCode: "230",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mauritius.svg",
      operatingCountry: false,
      countryCode3Chars: "MUS"
    },
    {
      countryCode: "YT",
      countryName: "Mayotte",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "262",
      flagPath: "https://restcountries.eu/data/myt.svg",
      operatingCountry: false,
      countryCode3Chars: "MYT"
    },
    {
      countryCode: "MX",
      countryName: "Mexico",
      currency: "MXN",
      currencySymbol: "$",
      nationality: "Mexican",
      dialCode: "52",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mexico.svg",
      operatingCountry: false,
      countryCode3Chars: "MEX"
    },
    {
      countryCode: "FM",
      countryName: "Micronesia (Federated States of)",
      currency: null,
      currencySymbol: "$",
      nationality: "Micronesian",
      dialCode: "691",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/micronesia.svg",
      operatingCountry: false,
      countryCode3Chars: "FSM"
    },
    {
      countryCode: "MD",
      countryName: "Moldova (Republic of)",
      currency: "MDL",
      currencySymbol: "L",
      nationality: "Moldovan",
      dialCode: "373",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/moldova.svg",
      operatingCountry: false,
      countryCode3Chars: "MDA"
    },
    {
      countryCode: "MC",
      countryName: "Monaco",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Monegasque",
      dialCode: "377",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/monaco.svg",
      operatingCountry: false,
      countryCode3Chars: "MCO"
    },
    {
      countryCode: "MN",
      countryName: "Mongolia",
      currency: "MNT",
      currencySymbol: "₮",
      nationality: "Mongolian",
      dialCode: "976",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mongolia.svg",
      operatingCountry: false,
      countryCode3Chars: "MNG"
    },
    {
      countryCode: "ME",
      countryName: "Montenegro",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Montenegrin",
      dialCode: "382",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/montenegro.svg",
      operatingCountry: false,
      countryCode3Chars: "MNE"
    },
    {
      countryCode: "MS",
      countryName: "Montserrat",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Montserratian",
      dialCode: "1664",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/montserrat.svg",
      operatingCountry: false,
      countryCode3Chars: "MSR"
    },
    {
      countryCode: "MA",
      countryName: "Morocco",
      currency: "MAD",
      currencySymbol: "د.م.",
      nationality: "Moroccan",
      dialCode: "212",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/morocco.svg",
      operatingCountry: false,
      countryCode3Chars: "MAR"
    },
    {
      countryCode: "MZ",
      countryName: "Mozambique",
      currency: "MZN",
      currencySymbol: "MT",
      nationality: "Mozambican",
      dialCode: "258",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/mozambique.svg",
      operatingCountry: false,
      countryCode3Chars: "MOZ"
    },
    {
      countryCode: "MM",
      countryName: "Myanmar",
      currency: "MMK",
      currencySymbol: "Ks",
      nationality: "Burmese",
      dialCode: "95",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/myanmar.svg",
      operatingCountry: false,
      countryCode3Chars: "MMR"
    },
    {
      countryCode: "NA",
      countryName: "Namibia",
      currency: "NAD",
      currencySymbol: "$",
      nationality: "Namibian",
      dialCode: "264",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/namibia.svg",
      operatingCountry: false,
      countryCode3Chars: "NAM"
    },
    {
      countryCode: "NR",
      countryName: "Nauru",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Nauruan",
      dialCode: "674",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/nauru.svg",
      operatingCountry: false,
      countryCode3Chars: "NRU"
    },
    {
      countryCode: "NP",
      countryName: "Nepal",
      currency: "NPR",
      currencySymbol: "₨",
      nationality: "Nepalese",
      dialCode: "977",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/nepal.svg",
      operatingCountry: false,
      countryCode3Chars: "NPL"
    },
    {
      countryCode: "NL",
      countryName: "Netherlands",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Dutch",
      dialCode: "31",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/netherlands.svg",
      operatingCountry: false,
      countryCode3Chars: "NLD"
    },
    {
      countryCode: "NC",
      countryName: "New Caledonia",
      currency: "XPF",
      currencySymbol: "Fr",
      nationality: "New Caledonian",
      dialCode: "687",
      flagPath: "https://restcountries.eu/data/ncl.svg",
      operatingCountry: false,
      countryCode3Chars: "NCL"
    },
    {
      countryCode: "NZ",
      countryName: "New Zealand",
      currency: "NZD",
      currencySymbol: "$",
      nationality: "New Zealander",
      dialCode: "64",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/new-zealand.svg",
      operatingCountry: false,
      countryCode3Chars: "NZL"
    },
    {
      countryCode: "NI",
      countryName: "Nicaragua",
      currency: "NIO",
      currencySymbol: "C$",
      nationality: "Nicaraguan",
      dialCode: "505",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/nicaragua.svg",
      operatingCountry: false,
      countryCode3Chars: "NIC"
    },
    {
      countryCode: "NE",
      countryName: "Niger",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Nigerien",
      dialCode: "227",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/niger.svg",
      operatingCountry: false,
      countryCode3Chars: "NER"
    },
    {
      countryCode: "NG",
      countryName: "Nigeria",
      currency: "NGN",
      currencySymbol: "₦",
      nationality: "Nigerian",
      dialCode: "234",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/nigeria.svg",
      operatingCountry: false,
      countryCode3Chars: "NGA"
    },
    {
      countryCode: "NU",
      countryName: "Niue",
      currency: "NZD",
      currencySymbol: "$",
      nationality: "Niuean",
      dialCode: "683",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/niue.svg",
      operatingCountry: false,
      countryCode3Chars: "NIU"
    },
    {
      countryCode: "NF",
      countryName: "Norfolk Island",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Norfolk Islander",
      dialCode: "672",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/norfolk-island.svg",
      operatingCountry: false,
      countryCode3Chars: "NFK"
    },
    {
      countryCode: "KP",
      countryName: "Korea (Democratic People's Republic of)",
      currency: "KPW",
      currencySymbol: "₩",
      nationality: "North Korean",
      dialCode: "850",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/north-korea.svg",
      operatingCountry: false,
      countryCode3Chars: "PRK"
    },
    {
      countryCode: "MP",
      countryName: "Northern Mariana Islands",
      currency: "USD",
      currencySymbol: "$",
      nationality: "American",
      dialCode: "1670",
      flagPath: "https://restcountries.eu/data/mnp.svg",
      operatingCountry: false,
      countryCode3Chars: "MNP"
    },
    {
      countryCode: "NO",
      countryName: "Norway",
      currency: "NOK",
      currencySymbol: "kr",
      nationality: "Norwegian",
      dialCode: "47",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/norway.svg",
      operatingCountry: false,
      countryCode3Chars: "NOR"
    },
    {
      countryCode: "OM",
      countryName: "Oman",
      currency: "OMR",
      currencySymbol: "ر.ع.",
      nationality: "Omani",
      dialCode: "968",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/oman.svg",
      operatingCountry: false,
      countryCode3Chars: "OMN"
    },
    {
      countryCode: "PK",
      countryName: "Pakistan",
      currency: "PKR",
      currencySymbol: "₨",
      nationality: "Pakistani",
      dialCode: "92",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/pakistan.svg",
      operatingCountry: false,
      countryCode3Chars: "PAK"
    },
    {
      countryCode: "PW",
      countryName: "Palau",
      currency: "(none)",
      currencySymbol: "$",
      nationality: "Palauan",
      dialCode: "680",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/palau.svg",
      operatingCountry: false,
      countryCode3Chars: "PLW"
    },
    {
      countryCode: "PS",
      countryName: "Palestine, State of",
      currency: "ILS",
      currencySymbol: "₪",
      nationality: "Palestinian",
      dialCode: "970",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/palestine.svg",
      operatingCountry: false,
      countryCode3Chars: "PSE"
    },
    {
      countryCode: "PA",
      countryName: "Panama",
      currency: "PAB",
      currencySymbol: "B/.",
      nationality: "Panamanian",
      dialCode: "507",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/panama.svg",
      operatingCountry: false,
      countryCode3Chars: "PAN"
    },
    {
      countryCode: "PG",
      countryName: "Papua New Guinea",
      currency: "PGK",
      currencySymbol: "K",
      nationality: "Papua New Guinean",
      dialCode: "675",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/papua-new-guinea.svg",
      operatingCountry: false,
      countryCode3Chars: "PNG"
    },
    {
      countryCode: "PY",
      countryName: "Paraguay",
      currency: "PYG",
      currencySymbol: "₲",
      nationality: "Paraguayan",
      dialCode: "595",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/paraguay.svg",
      operatingCountry: false,
      countryCode3Chars: "PRY"
    },
    {
      countryCode: "PE",
      countryName: "Peru",
      currency: "PEN",
      currencySymbol: "S/.",
      nationality: "Peruvian",
      dialCode: "51",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/peru.svg",
      operatingCountry: false,
      countryCode3Chars: "PER"
    },
    {
      countryCode: "PH",
      countryName: "Philippines",
      currency: "PHP",
      currencySymbol: "₱",
      nationality: "Filipino",
      dialCode: "63",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/philippines.svg",
      operatingCountry: false,
      countryCode3Chars: "PHL"
    },
    {
      countryCode: "PN",
      countryName: "Pitcairn",
      currency: "NZD",
      currencySymbol: "$",
      nationality: "Pitcairn Islander",
      dialCode: "64",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/pitcairn-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "PCN"
    },
    {
      countryCode: "PL",
      countryName: "Poland",
      currency: "PLN",
      currencySymbol: "zł",
      nationality: "Polish",
      dialCode: "48",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/republic-of-poland.svg",
      operatingCountry: false,
      countryCode3Chars: "POL"
    },
    {
      countryCode: "PT",
      countryName: "Portugal",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Portuguese",
      dialCode: "351",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/portugal.svg",
      operatingCountry: false,
      countryCode3Chars: "PRT"
    },
    {
      countryCode: "PR",
      countryName: "Puerto Rico",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Puerto Rican",
      dialCode: "1787",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/puerto-rico.svg",
      operatingCountry: false,
      countryCode3Chars: "PRI"
    },
    {
      countryCode: "QA",
      countryName: "Qatar",
      currency: "QAR",
      currencySymbol: "ر.ق",
      nationality: "Qatari",
      dialCode: "974",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/qatar.svg",
      operatingCountry: false,
      countryCode3Chars: "QAT"
    },
    {
      countryCode: "XK",
      countryName: "Republic of Kosovo",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Kosovar",
      dialCode: "383",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/kosovo.svg",
      operatingCountry: false,
      countryCode3Chars: "KOS"
    },
    {
      countryCode: "RE",
      countryName: "Réunion",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "262",
      flagPath: "https://restcountries.eu/data/reu.svg",
      operatingCountry: false,
      countryCode3Chars: "REU"
    },
    {
      countryCode: "RO",
      countryName: "Romania",
      currency: "RON",
      currencySymbol: "lei",
      nationality: "Romanian",
      dialCode: "40",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/romania.svg",
      operatingCountry: false,
      countryCode3Chars: "ROU"
    },
    {
      countryCode: "RU",
      countryName: "Russian Federation",
      currency: "RUB",
      currencySymbol: "₽",
      nationality: "Russian",
      dialCode: "7",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/russia.svg",
      operatingCountry: false,
      countryCode3Chars: "RUS"
    },
    {
      countryCode: "RW",
      countryName: "Rwanda",
      currency: "RWF",
      currencySymbol: "Fr",
      nationality: "Rwandan",
      dialCode: "250",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/rwanda.svg",
      operatingCountry: true,
      countryCode3Chars: "RWA"
    },
    {
      countryCode: "BL",
      countryName: "Saint Barthélemy",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Saint Barthélemy Islander",
      dialCode: "590",
      flagPath: "https://restcountries.eu/data/blm.svg",
      operatingCountry: false,
      countryCode3Chars: "BLM"
    },
    {
      countryCode: "SH",
      countryName: "Saint Helena, Ascension and Tristan da Cunha",
      currency: "SHP",
      currencySymbol: "£",
      nationality: "Saint Helenian",
      dialCode: "290",
      flagPath: "https://restcountries.eu/data/shn.svg",
      operatingCountry: false,
      countryCode3Chars: "SHN"
    },
    {
      countryCode: "KN",
      countryName: "Saint Kitts and Nevis",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Kittian and Nevisian",
      dialCode: "1869",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/saint-kitts-and-nevis.svg",
      operatingCountry: false,
      countryCode3Chars: "KNA"
    },
    {
      countryCode: "LC",
      countryName: "Saint Lucia",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Saint Lucian",
      dialCode: "1758",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/st-lucia.svg",
      operatingCountry: false,
      countryCode3Chars: "LCA"
    },
    {
      countryCode: "MF",
      countryName: "Saint Martin (French part)",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Saint Martin Islander",
      dialCode: "590",
      flagPath: "https://restcountries.eu/data/maf.svg",
      operatingCountry: false,
      countryCode3Chars: "MAF"
    },
    {
      countryCode: "PM",
      countryName: "Saint Pierre and Miquelon",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "French",
      dialCode: "508",
      flagPath: "https://restcountries.eu/data/spm.svg",
      operatingCountry: false,
      countryCode3Chars: "SPM"
    },
    {
      countryCode: "VC",
      countryName: "Saint Vincent and the Grenadines",
      currency: "XCD",
      currencySymbol: "$",
      nationality: "Saint Vincentian",
      dialCode: "1784",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/st-vincent-and-the-grenadines.svg",
      operatingCountry: false,
      countryCode3Chars: "VCT"
    },
    {
      countryCode: "WS",
      countryName: "Samoa",
      currency: "WST",
      currencySymbol: "T",
      nationality: "Samoan",
      dialCode: "685",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/samoa.svg",
      operatingCountry: false,
      countryCode3Chars: "WSM"
    },
    {
      countryCode: "SM",
      countryName: "San Marino",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Sammarinese",
      dialCode: "378",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/san-marino.svg",
      operatingCountry: false,
      countryCode3Chars: "SMR"
    },
    {
      countryCode: "ST",
      countryName: "Sao Tome and Principe",
      currency: "STD",
      currencySymbol: "Db",
      nationality: "Sao Tomean",
      dialCode: "239",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sao-tome-and-principe.svg",
      operatingCountry: false,
      countryCode3Chars: "STP"
    },
    {
      countryCode: "SA",
      countryName: "Saudi Arabia",
      currency: "SAR",
      currencySymbol: "ر.س",
      nationality: "Saudi Arabian",
      dialCode: "966",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/saudi-arabia.svg",
      operatingCountry: false,
      countryCode3Chars: "SAU"
    },
    {
      countryCode: "SN",
      countryName: "Senegal",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Senegalese",
      dialCode: "221",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/senegal.svg",
      operatingCountry: false,
      countryCode3Chars: "SEN"
    },
    {
      countryCode: "RS",
      countryName: "Serbia",
      currency: "RSD",
      currencySymbol: "дин.",
      nationality: "Serbian",
      dialCode: "381",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/serbia.svg",
      operatingCountry: false,
      countryCode3Chars: "SRB"
    },
    {
      countryCode: "SC",
      countryName: "Seychelles",
      currency: "SCR",
      currencySymbol: "₨",
      nationality: "Seychellois",
      dialCode: "248",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/seychelles.svg",
      operatingCountry: false,
      countryCode3Chars: "SYC"
    },
    {
      countryCode: "SL",
      countryName: "Sierra Leone",
      currency: "SLL",
      currencySymbol: "Le",
      nationality: "Sierra Leonean",
      dialCode: "232",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sierra-leone.svg",
      operatingCountry: false,
      countryCode3Chars: "SLE"
    },
    {
      countryCode: "SG",
      countryName: "Singapore",
      currency: "BND",
      currencySymbol: "$",
      nationality: "Singaporean",
      dialCode: "65",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/singapore.svg",
      operatingCountry: false,
      countryCode3Chars: "SGP"
    },
    {
      countryCode: "SX",
      countryName: "Sint Maarten (Dutch part)",
      currency: "ANG",
      currencySymbol: "ƒ",
      nationality: "Dutch",
      dialCode: "1721",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sint-maarten.svg",
      operatingCountry: false,
      countryCode3Chars: "SXM"
    },
    {
      countryCode: "SK",
      countryName: "Slovakia",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Slovak",
      dialCode: "421",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/slovakia.svg",
      operatingCountry: false,
      countryCode3Chars: "SVK"
    },
    {
      countryCode: "SI",
      countryName: "Slovenia",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Slovene",
      dialCode: "386",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/slovenia.svg",
      operatingCountry: false,
      countryCode3Chars: "SVN"
    },
    {
      countryCode: "SB",
      countryName: "Solomon Islands",
      currency: "SBD",
      currencySymbol: "$",
      nationality: "Solomon Islander",
      dialCode: "677",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/solomon-islands.svg",
      operatingCountry: false,
      countryCode3Chars: "SLB"
    },
    {
      countryCode: "SO",
      countryName: "Somalia",
      currency: "SOS",
      currencySymbol: "Sh",
      nationality: "Somali",
      dialCode: "252",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/somalia.svg",
      operatingCountry: false,
      countryCode3Chars: "SOM"
    },
    {
      countryCode: "ZA",
      countryName: "South Africa",
      currency: "ZAR",
      currencySymbol: "R",
      nationality: "South African",
      dialCode: "27",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/south-africa.svg",
      operatingCountry: false,
      countryCode3Chars: "ZAF"
    },
    {
      countryCode: "GS",
      countryName: "South Georgia and the South Sandwich Islands",
      currency: "GBP",
      currencySymbol: "£",
      nationality: "South Georgia and the South Sandwich Islander",
      dialCode: "500",
      flagPath: "https://restcountries.eu/data/sgs.svg",
      operatingCountry: false,
      countryCode3Chars: "SGS"
    },
    {
      countryCode: "KR",
      countryName: "South Korea",
      currency: "KRW",
      currencySymbol: "₩",
      nationality: "South Korean",
      dialCode: "82",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/south-korea.svg",
      operatingCountry: false,
      countryCode3Chars: "KOR"
    },
    {
      countryCode: "SS",
      countryName: "South Sudan",
      currency: "SSP",
      currencySymbol: "£",
      nationality: "South Sudanese",
      dialCode: "211",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/south-sudan.svg",
      operatingCountry: true,
      countryCode3Chars: "SSD"
    },
    {
      countryCode: "ES",
      countryName: "Spain",
      currency: "EUR",
      currencySymbol: "€",
      nationality: "Spanish",
      dialCode: "34",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/europe.svg",
      operatingCountry: false,
      countryCode3Chars: "ESP"
    },
    {
      countryCode: "LK",
      countryName: "Sri Lanka",
      currency: "LKR",
      currencySymbol: "Rs",
      nationality: "Sri Lankan",
      dialCode: "94",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sri-lanka.svg",
      operatingCountry: false,
      countryCode3Chars: "LKA"
    },
    {
      countryCode: "SD",
      countryName: "Sudan",
      currency: "SDG",
      currencySymbol: "ج.س.",
      nationality: "Sudanese",
      dialCode: "249",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sudan.svg",
      operatingCountry: false,
      countryCode3Chars: "SDN"
    },
    {
      countryCode: "SR",
      countryName: "Suriname",
      currency: "SRD",
      currencySymbol: "$",
      nationality: "Surinamer",
      dialCode: "597",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/suriname.svg",
      operatingCountry: false,
      countryCode3Chars: "SUR"
    },
    {
      countryCode: "SJ",
      countryName: "Svalbard and Jan Mayen",
      currency: "NOK",
      currencySymbol: "kr",
      nationality: "Norwegian",
      dialCode: "4779",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/norway.svg",
      operatingCountry: false,
      countryCode3Chars: "SJM"
    },
    {
      countryCode: "SZ",
      countryName: "Swaziland",
      currency: "SZL",
      currencySymbol: "L",
      nationality: "Swazi",
      dialCode: "268",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/swaziland.svg",
      operatingCountry: false,
      countryCode3Chars: "SWZ"
    },
    {
      countryCode: "SE",
      countryName: "Sweden",
      currency: "SEK",
      currencySymbol: "kr",
      nationality: "Swedish",
      dialCode: "46",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/sweden.svg",
      operatingCountry: false,
      countryCode3Chars: "SWE"
    },
    {
      countryCode: "CH",
      countryName: "Switzerland",
      currency: "CHF",
      currencySymbol: "Fr",
      nationality: "Swiss",
      dialCode: "41",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/switzerland.svg",
      operatingCountry: false,
      countryCode3Chars: "CHE"
    },
    {
      countryCode: "SY",
      countryName: "Syrian Arab Republic",
      currency: "SYP",
      currencySymbol: "£",
      nationality: "Syrian",
      dialCode: "963",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/syria.svg",
      operatingCountry: false,
      countryCode3Chars: "SYR"
    },
    {
      countryCode: "TW",
      countryName: "Taiwan",
      currency: "TWD",
      currencySymbol: "$",
      nationality: "Taiwanese",
      dialCode: "886",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/taiwan.svg",
      operatingCountry: false,
      countryCode3Chars: "TWN"
    },
    {
      countryCode: "TJ",
      countryName: "Tajikistan",
      currency: "TJS",
      currencySymbol: "ЅМ",
      nationality: "Tadzhik",
      dialCode: "992",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tajikistan.svg",
      operatingCountry: false,
      countryCode3Chars: "TJK"
    },
    {
      countryCode: "TZ",
      countryName: "Tanzania, United Republic of",
      currency: "TZS",
      currencySymbol: "Sh",
      nationality: "Tanzanian",
      dialCode: "255",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tanzania.svg",
      operatingCountry: true,
      countryCode3Chars: "TZA"
    },
    {
      countryCode: "TH",
      countryName: "Thailand",
      currency: "THB",
      currencySymbol: "฿",
      nationality: "Thai",
      dialCode: "66",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/thailand.svg",
      operatingCountry: false,
      countryCode3Chars: "THA"
    },
    {
      countryCode: "TL",
      countryName: "Timor-Leste",
      currency: "USD",
      currencySymbol: "$",
      nationality: "East Timorese",
      dialCode: "670",
      flagPath: "https://restcountries.eu/data/tls.svg",
      operatingCountry: false,
      countryCode3Chars: "TLS"
    },
    {
      countryCode: "TG",
      countryName: "Togo",
      currency: "XOF",
      currencySymbol: "Fr",
      nationality: "Togolese",
      dialCode: "228",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/togo.svg",
      operatingCountry: false,
      countryCode3Chars: "TGO"
    },
    {
      countryCode: "TK",
      countryName: "Tokelau",
      currency: "NZD",
      currencySymbol: "$",
      nationality: "Tokelauan",
      dialCode: "690",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tokelau.svg",
      operatingCountry: false,
      countryCode3Chars: "TKL"
    },
    {
      countryCode: "TO",
      countryName: "Tonga",
      currency: "TOP",
      currencySymbol: "T$",
      nationality: "Tongan",
      dialCode: "676",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tonga.svg",
      operatingCountry: false,
      countryCode3Chars: "TON"
    },
    {
      countryCode: "TT",
      countryName: "Trinidad and Tobago",
      currency: "TTD",
      currencySymbol: "$",
      nationality: "Trinidadian",
      dialCode: "1868",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/trinidad-and-tobago.svg",
      operatingCountry: false,
      countryCode3Chars: "TTO"
    },
    {
      countryCode: "TN",
      countryName: "Tunisia",
      currency: "TND",
      currencySymbol: "د.ت",
      nationality: "Tunisian",
      dialCode: "216",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tunisia.svg",
      operatingCountry: false,
      countryCode3Chars: "TUN"
    },
    {
      countryCode: "TR",
      countryName: "Turkey",
      currency: "TRY",
      currencySymbol: null,
      nationality: "Turkish",
      dialCode: "90",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/turkey.svg",
      operatingCountry: false,
      countryCode3Chars: "TUR"
    },
    {
      countryCode: "TM",
      countryName: "Turkmenistan",
      currency: "TMT",
      currencySymbol: "m",
      nationality: "Turkmen",
      dialCode: "993",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/turkmenistan.svg",
      operatingCountry: false,
      countryCode3Chars: "TKM"
    },
    {
      countryCode: "TC",
      countryName: "Turks and Caicos Islands",
      currency: "USD",
      currencySymbol: "$",
      nationality: "Turks and Caicos Islander",
      dialCode: "1649",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/turks-and-caicos.svg",
      operatingCountry: false,
      countryCode3Chars: "TCA"
    },
    {
      countryCode: "TV",
      countryName: "Tuvalu",
      currency: "AUD",
      currencySymbol: "$",
      nationality: "Tuvaluan",
      dialCode: "688",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/tuvalu.svg",
      operatingCountry: false,
      countryCode3Chars: "TUV"
    },
    {
      countryCode: "UG",
      countryName: "Uganda",
      currency: "UGX",
      currencySymbol: "Sh",
      nationality: "Ugandan",
      dialCode: "256",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/uganda.svg",
      operatingCountry: true,
      countryCode3Chars: "UGA"
    },
    {
      countryCode: "UA",
      countryName: "Ukraine",
      currency: "UAH",
      currencySymbol: "₴",
      nationality: "Ukrainian",
      dialCode: "380",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/ukraine.svg",
      operatingCountry: false,
      countryCode3Chars: "UKR"
    },
    {
      countryCode: "AE",
      countryName: "United Arab Emirates",
      currency: "AED",
      currencySymbol: "د.إ",
      nationality: "Emirati",
      dialCode: "971",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-arab-emirates.svg",
      operatingCountry: false,
      countryCode3Chars: "ARE"
    },
    {
      countryCode: "GB",
      countryName: "United Kingdom of Great Britain and Northern Ireland",
      currency: "GBP",
      currencySymbol: "£",
      nationality: "British",
      dialCode: "44",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-kingdom.svg",
      operatingCountry: false,
      countryCode3Chars: "GBR"
    },
    {
      countryCode: "US",
      countryName: "United States of America",
      currency: "USD",
      currencySymbol: "$",
      nationality: "American",
      dialCode: "1",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/united-states-of-america.svg",
      operatingCountry: false,
      countryCode3Chars: "USA"
    },
    {
      countryCode: "UY",
      countryName: "Uruguay",
      currency: "UYU",
      currencySymbol: "$",
      nationality: "Uruguayan",
      dialCode: "598",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/uruguay.svg",
      operatingCountry: false,
      countryCode3Chars: "URY"
    },
    {
      countryCode: "UZ",
      countryName: "Uzbekistan",
      currency: "UZS",
      currencySymbol: null,
      nationality: "Uzbekistani",
      dialCode: "998",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/uzbekistn.svg",
      operatingCountry: false,
      countryCode3Chars: "UZB"
    },
    {
      countryCode: "VU",
      countryName: "Vanuatu",
      currency: "VUV",
      currencySymbol: "Vt",
      nationality: "Ni-Vanuatu",
      dialCode: "678",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/vanuatu.svg",
      operatingCountry: false,
      countryCode3Chars: "VUT"
    },
    {
      countryCode: "VE",
      countryName: "Venezuela (Bolivarian Republic of)",
      currency: "VEF",
      currencySymbol: "Bs F",
      nationality: "Venezuelan",
      dialCode: "58",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/venezuela.svg",
      operatingCountry: false,
      countryCode3Chars: "VEN"
    },
    {
      countryCode: "VN",
      countryName: "Vietnam",
      currency: "VND",
      currencySymbol: "₫",
      nationality: "Vietnamese",
      dialCode: "84",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/vietnam.svg",
      operatingCountry: false,
      countryCode3Chars: "VNM"
    },
    {
      countryCode: "WF",
      countryName: "Wallis and Futuna",
      currency: "XPF",
      currencySymbol: "Fr",
      nationality: "Wallis and Futuna Islander",
      dialCode: "681",
      flagPath: "https://restcountries.eu/data/wlf.svg",
      operatingCountry: false,
      countryCode3Chars: "WLF"
    },
    {
      countryCode: "EH",
      countryName: "Western Sahara",
      currency: "MAD",
      currencySymbol: "د.م.",
      nationality: "Sahrawi",
      dialCode: "212",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/western-sahara.svg",
      operatingCountry: false,
      countryCode3Chars: "ESH"
    },
    {
      countryCode: "YE",
      countryName: "Yemen",
      currency: "YER",
      currencySymbol: "﷼",
      nationality: "Yemeni",
      dialCode: "967",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/yemen.svg",
      operatingCountry: false,
      countryCode3Chars: "YEM"
    },
    {
      countryCode: "ZM",
      countryName: "Zambia",
      currency: "ZMW",
      currencySymbol: "ZK",
      nationality: "Zambian",
      dialCode: "260",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/zambia.svg",
      operatingCountry: false,
      countryCode3Chars: "ZMB"
    },
    {
      countryCode: "ZW",
      countryName: "Zimbabwe",
      currency: "BWP",
      currencySymbol: "P",
      nationality: "Zimbabwean",
      dialCode: "263",
      flagPath: "https://oneequity.blob.core.windows.net/assets/visuals/flags/zimbabwe.svg",
      operatingCountry: false,
      countryCode3Chars: "ZWE"
    }
];
